修复了换行的问题

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -16,8 +16,8 @@ jobs:
           sudo apt-get install cmake build-essential "$CUSTOM_APT_INSTALL" -y
       - name: test_cmake
         run: | 
-           cmake . && CMakeFlag=1 || (echo "[ERROR] CMake Failed, Please Check Your CMakelists.txt\n[错误] 你的CMake配置存在问题，请检查你的CMakeLists.txt！\n [note]如果你需要使用某些第三方依赖,请修改env文件,添加上所需要的依赖。" ; CMakeFlag=0 && exit 1)
-           test 1 -eq $CMakeFlag && make || echo "[ERROR] Make Failed! \n [错误] 编译失败。" && exit 1
+           cmake . && CMakeFlag=1 || (echo -e "[ERROR] CMake Failed, Please Check Your CMakelists.txt\n[错误] 你的CMake配置存在问题，请检查你的CMakeLists.txt！\n [note]如果你需要使用某些第三方依赖,请修改env文件,添加上所需要的依赖。" ; CMakeFlag=0 && exit 1)
+           test 1 -eq $CMakeFlag && make || echo -e "[ERROR] Make Failed! \n [错误] 编译失败。" && exit 1
       - name: test_run
         run: |
           source .github/customs/envs
