尝试修复一个奇怪的Error提示

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -25,7 +25,7 @@ jobs:
           echo -e "[INFO] Environment Setup Done! \n [信息] 环境配置完成！"
       - name: test_cmake
         run: | 
-           cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && CMakeFlag=1 || (echo -e "[ERROR] CMake Failed, Please Check Your CMakelists.txt\n[错误] 你的CMake配置存在问题，请检查你的CMakeLists.txt！\n[note] 如果你需要使用某些第三方依赖,请修改env文件,添加上所需要的依赖。" ; CMakeFlag=0 && exit 1)
+           cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} && CMakeFlag=1 || (echo -e "CMake Failed, Please Check Your CMakelists.txt\n[错误] 你的CMake配置存在问题，请检查你的CMakeLists.txt！\n[note] 如果你需要使用某些第三方依赖,请修改env文件,添加上所需要的依赖。" ; CMakeFlag=0 && exit 1)
            test 1 -eq $CMakeFlag && cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
            echo -e "[INFO] CMake Done! \n [信息] CMake&Make执行完成！"
 
